server:
  port: 8080

spring:
  application:
    name: ceremony-server-ai
#  datasource:
#    url: jdbc:mysql://localhost:3306/ceremony_ai?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
#    hibernate:
#      ddl-auto: update
#    show-sql: true
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
#          model: deepseek-r1:8b
          model: ishumilin/deepseek-r1-coder-tools:1.5b
          temperature: 0.7
          top-p: 0.95
          repeat-penalty: 1.1
      embedding:
        options:
          model: deepseek-r1:8b
    mcp:
      server:
        name: webflux-mcp-server
        type: SYNC
#      本地服务需要打成jar包
#        name: stdio-mcp-server
#        stdio: true
        version: 1.0.0
#  main:
#    banner-mode: off
#    web-application-type: none