server:
  port: 8080

spring:
  application:
    name: ceremony-server-ai
  datasource:
    url: jdbc:mysql://localhost:3306/ceremony_ai?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  ai:
    ollama:
      base-url: http://localhost:11434
      model: deepseek-r1:8b