server:
  port: 8081

spring:
  ai:
    client:
      sse:
        connections:
          server1:
            url: http://localhost:8080
#      stdio:
#        root-change-notification: false
#        servers-configuration: classpath:mcp-servers.json

